server:
  port: 8080
  servlet:
    context-path: /zhangbingbing
  error:
    include-exception: true
    include-stacktrace: always
spring:
  profiles:
    active: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mall?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
person:
  name: zhangsan
  age: 18
  sex: 男
  birthDate: 1991/01/01
  pets: [cat,dog,pig]
  cars:
    - dazhao
    - audi
    - jieda
  maps: {k1: v1,k2: v2}
  girlfriend:
    name: xiaohao
    age: 18
---
# 开发环境配置
spring:
  profiles: dev
server:
  port: 8080
---
# 生产环境配置
spring:
  profiles: prod
server:
  port: 8082


